[project]
name = "evo-sdk-common"
description = "Python package that establishes a common framework for use by client libraries that interact with Seequent Evo APIs"
version = "0.5.10"
requires-python = ">=3.10"
license-files = ["LICENSE.md"]
dynamic = ["readme"]
authors = [
    { name = "Seequent", email = "support@seequent.com" }
]

dependencies = [
    # Specify the minimum versions to avoid security issues.
    "pure-interface>=8.0.0",
    "pydantic>=2",
    "python-dateutil",
]

[project.urls]
Source = "https://github.com/SeequentEvo/evo-python-sdk"
Tracker = "https://github.com/SeequentEvo/evo-python-sdk/issues"
Homepage = "https://www.seequent.com/"
Documentation = "https://developer.seequent.com/"

[project.optional-dependencies]
aiohttp = ["aiohttp"]
notebooks = [
    "evo-sdk-common[aiohttp]",
    "ipykernel",
    "ipython",
    "ipywidgets",
    "python-dotenv"
]
jmespath = [
    "jmespath>=1.0.1",
]

[dependency-groups]
# Dev dependencies. The version is left unspecified so the latest is installed.
test = [
    "evo-sdk-common[aiohttp]",
    "freezegun",
    "parameterized==0.9.0",
    "pytest",
]
dev = [
    "evo-sdk-common[aiohttp,jmespath]",
    "bumpver",
    "coverage[toml]",
    "ruff==0.14.0", # keep in sync with .pre-commit-config.yaml
    "pre-commit",
    {include-group="test"},
]
notebooks = [
    "evo-sdk-common[aiohttp,notebooks]",
    "jupyter",
]

[tool.ruff]
src = ["src", "tests"]
line-length = 120

[tool.ruff.lint]
extend-select = ["I", "RUF022"]

[build-system]
requires = ["hatchling", "hatch-fancy-pypi-readme"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.sdist]
include = ["src", "assets"]

[tool.hatch.build.targets.wheel]
packages = ["src/evo"]

[tool.hatch.metadata.hooks.fancy-pypi-readme]
content-type = "text/markdown"

[[tool.hatch.metadata.hooks.fancy-pypi-readme.fragments]]
path = "README.md"

[[tool.hatch.metadata.hooks.fancy-pypi-readme.substitutions]]
# Literal TOML strings (single quotes) need no escaping of backslashes.
# Converts relative links to absolute links in PyPI
pattern = '\[(.+?)\]\(((?!https?://)\S+?)\)'
replacement = '[\1](https://github.com/SeequentEvo/evo-python-sdk/tree/main/packages/$HFPR_PACKAGE_NAME/\g<2>)'
