repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.14.0 # keep in sync with pyproject.toml
    hooks:
      - id: ruff
        name: Run linter
      - id: ruff-format
        name: Run formatter
        args: ["--check"]
  - repo: https://github.com/kynan/nbstripout
    rev: 0.8.1
    hooks:
      - id: nbstripout
        name: Strip outputs from Jupyter notebooks
