name: Audit commits

on:
  pull_request:

permissions:
  contents: read
  pull-requests: read

env:
  PR_NUMBER: ${{ github.event.number }}
  GH_TOKEN: ${{ github.token }}

jobs:
  audit-commits:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check for organisation email addresses in commits
        shell: bash
        run: |
          EMAILS=$(gh pr view ${{ env.PR_NUMBER }} --json commits | jq .commits[].authors[].email)
          if [[ $(echo $EMAILS | grep -i "@seequent.com") || $(echo $EMAILS | grep -i "@bentley.com") ]]; then
            echo "Please enable 'no-reply' commit settings in your GitHub account"
            echo "See https://docs.github.com/articles/setting-your-email-in-git"
            exit 1
          fi
